version: '3.1'

services:

  node:
    build: ./services/node
    volumes: 
      - ../:/app/
    ports:
      - 4100:4100
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true